/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AboutSection: typeof import('./components/about/AboutSection.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseDevider: typeof import('./components/base/BaseDivider.vue')['default']
    BaseDivider: typeof import('./components/base/BaseDivider.vue')['default']
    BaseSection: typeof import('./components/base/BaseSection.vue')['default']
    BaseTable: typeof import('./components/base/BaseTable.vue')['default']
    BlogArticle: typeof import('./components/blog/BlogArticle.vue')['default']
    BlogSection: typeof import('./components/blog/BlogSection.vue')['default']
    BlogTag: typeof import('./components/blog/BlogTag.vue')['default']
    ContactSection: typeof import('./components/contact/ContactSection.vue')['default']
    copy: typeof import('./components/products/ProductCard copy.vue')['default']
    GuidesSection: typeof import('./components/guides/GuidesSection.vue')['default']
    HeroQuote: typeof import('./components/hero/HeroQuote.vue')['default']
    HeroSection: typeof import('./components/hero/HeroSection.vue')['default']
    LocationExpertise: typeof import('./components/location-expertise/LocationExpertise.vue')['default']
    ProductCard: typeof import('./components/products/ProductCard.vue')['default']
    ProductCardLarge: typeof import('./components/products/ProductCardLarge.vue')['default']
    ProductsSection: typeof import('./components/products/ProductsSection.vue')['default']
    ProjectCard: typeof import('./components/projects/ProjectCard.vue')['default']
    ProjectsSection: typeof import('./components/projects/ProjectsSection.vue')['default']
    QuestionSection: typeof import('./components/questions/QuestionSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./components/services/ServiceCard.vue')['default']
    ServicesSection: typeof import('./components/services/ServicesSection.vue')['default']
    TeamCard: typeof import('./components/team/TeamCard.vue')['default']
    TeamSection: typeof import('./components/team/TeamSection.vue')['default']
  }
}
